---
version: "2.0"
services:
  web:
    image: decentland/molext-1
    env:
      - HACKERNOON_API_KEY=<YOUR_API_KEY>
      - MORALIS_API_TOKEN=<YOUR_API_KEY>
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000
deployment:
  web:
    dcloud:
      profile: web
      count: 1
